controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    three_r_arm_controller:
      type: forward_command_controller/ForwardCommandController


three_r_arm_controller:
  ros__parameters:

    joints:
      - joint1
      - joint2
      - joint3

    interface_name: position